### ISSUE TITLE
Plugin breaks markdown tables

### ISSUE THREAD

**Issue by LunaticMuch** [tetracalibers/astro-mdx-directive#1]
There's an issue with the plugin as it breaks markdown tables.
When you have it installed, then remark does not render tables anymore.

**Comment by tetracalibers** [comment]
@LunaticMuch 

Thank you so much for reporting the bug. I sincerely apologize for the delay in addressing this issue. 
I'm pleased to inform you that the bug you reported has been resolved in the latest release, version 1.0.0. 

- [Changelog - v1.0.0](https://github.com/tetracalibers/astro-mdx-directive/blob/main/CHANGELOG.md#v100---2024-03-16)

We greatly appreciate your contribution to improving the package.
